debug:
  # 是否在后台输出插件信息
  enable: true
  # 是否在后台输出收到的数据
  receive: true
  # 是否在后台输出发送的数据
  send: true
  # 是否在后台输出连接状态
  connect: true
  # 是否在后台输出注册信息
  register: true

# 服务地址
host: "localhost"
# 服务端口
port: 8520
# 密码
password: "password"